"""Init

Revision ID: 04bac15629ca
Revises: 456f4b6d1024
Create Date: 2023-08-24 13:20:54.500922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bac15629ca'
down_revision: Union[str, None] = '456f4b6d1024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_info_email'), 'users_info', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_info_email'), table_name='users_info')
    op.drop_column('users_info', 'email')
    # ### end Alembic commands ###
